mysql:
  host: <mysql-host>
  user: <mysql-user>
  password: <mysql-password>
  database: <mysql-db>
  port: <mysql-port>

toit:
  username: <toit-username>
  password: <toit-password>
  data_topic_subscription: <toit-subscription-name>

web:
  port: 8081
  serve_path: ./web
  path: /track-devices
